### ISSUE TITLE
make the number of columns to be dynamic

### ISSUE THREAD

**Issue by felexkemboi** [felexkemboi/4thProject#5]
Our initial code is not dynamic for the case of selecting the number of columns.If anyone is upto the challenge kindly pick the task and go ahead.I would like to have the user to determine the length of the  column.Make sure you include infinity in your list
@kelvinziroh you can check this please

**Comment by kelvinziroh** [comment]
On it. Let me try it and see how it goes 👍

**Comment by felexkemboi** [comment]
Cheers!
