### ISSUE TITLE
where to prompt the user

### ISSUE THREAD

**Issue by felexkemboi** [felexkemboi/4thProject#6]
now that we will be forced to get users input in order to make our program dynamic.at what part are we suppose to prompt our user to enter the dimensions of the matrix,will it be outside or inside the function.Anyone who is up to the challenge to help in solving it please
@ogambakerubo i prefer you pick this

**Comment by ogambakerubo** [comment]
prompt user for input inside matrix function

**Comment by felexkemboi** [comment]
what do you mean by matrix....guess its matrix function
